apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    app: springbootapp
spec:
  selector:
    app: springbootapp
  type: LoadBalancer
  ports:
    - nodePort: 30032 
      port: 80 
      targetPort: 9099

